### ISSUE TITLE
SendmailanAlyzer does not display all shipments

### ISSUE THREAD

**Issue by laurentvv** [darold/sendmailanalyzer#22] opened 2014-09-15 07:43 UTC
Hello,

All shipments are not listed.
Today, for example, is shown in 1800 shipments.
If I do a search in / var / log / maillog, I said more than 10,000 email sent.
As this problem?

Thank you in advance.

**Comment by darold** [comment] 2015-02-18 13:22
I'm closing this issue because there's no other reports like that and some commit since this post may have solves the issue. I'm not able to reproduce the problem. Feel free to reopen this issue if the problem persist.

Best regards

**Closed by darold** 2015-02-18 13:22 UTC
